# This conda environment solves the package dependencies needed in DTox.

# To use:
# 
# $ conda env create -f environment.yml
# $ conda activate DTox

name: DTox
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - jupyter=1.0.0
  - jupyter_client=7.3.5 
  - jupyter_core=4.11.1
  - nbconvert=7.0.0 
  - python=3.7.3
  - numpy=1.21.2
  - pandas=1.3.3
  - joblib=1.2.0
  - scikit-learn=0.23.2
  - statsmodels=0.9.0
  - pytest=4.3.1
  - pip=19.0.3 
  - pip:
    - torch==1.10.1
  - r-base=3.6.3
  - r-RColorBrewer
  - r-visNetwork
